# Site
title:              N4O
description:        'Fagsubber, encoder, and "programmer"'
locale:             en_US
url:                https://shigoto.n4o.xyz
avatar:             https://p.n4o.xyz/i/ffe456.png
logo:               https://p.n4o.xyz/i/nao250px.png
notfoundimage:      https://static.thenounproject.com/png/801773-200.png
author:             N4O

timezone: "Asia/Jakarta"

# Jekyll
permalink:          /r/:title
paginate:           8
paginate_path:      /release/page:num
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false

# Custom
disqus_shortname:   n4oblog
naotimes_discordid: '472705451117641729'

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

sass:
  sass_dir: _scss

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, runserver.bat, runserverdrafts.bat]
include: [_redirects]
