[[redirects]]
    from = "/blog"
    to = "https://blog.n4o.xyz/"
    status = 301
    force = true

[[redirects]]
    from = "/blog/*"
    to = "https://blog.n4o.xyz/posts/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/blog/posts"
    to = "https://n4oblog.netlify.app/posts"
    status = 301
    force = true
